name: Docker Image CI
on: 
  pull_request:
    branches:
      - develop
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:

  BuildAndPush:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          file: "./Dockerfile"
          push: true
          context: .
          tags: mangatasolutions/mangata-healthcheck:${{ github.sha }}
     